/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export const projectModel = {
  languages: {
    default: {
      codename: 'default',
      name: 'Default project language',
    },
  },
  contentTypes: {
    homepage: {
      codename: 'homepage',
      name: 'Homepage',
      elements: {
        youtube_feeds: {
          codename: 'youtube_feeds',
          name: 'Youtube feeds',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        youtube_tile: {
          codename: 'youtube_tile',
          name: 'Youtube tile',
        },
        ondrejs: {
          codename: 'ondrejs',
          name: 'Ondrejs',
        },
      },
    },
    ondrej: {
      codename: 'ondrej',
      name: 'Ondrej',
      elements: {
        name: {
          codename: 'name',
          name: 'Name',
        },
        profile_photo: {
          codename: 'profile_photo',
          name: 'Profile Photo',
        },
      },
    },
    youtube_feed: {
      codename: 'youtube_feed',
      name: 'Youtube feed',
      elements: {
        url: {
          codename: 'url',
          name: 'URL',
        },
      },
    },
  },
  taxonomies: {},
};
