import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Homepage = IContentItem<{
  youtubeFeeds: Elements.LinkedItemsElement<IContentItem>;
  title: Elements.TextElement;
  youtubeTile: Elements.AssetsElement;
  ondrejs: Elements.LinkedItemsElement<IContentItem>;
}>;
